server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: gateway-service
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
  cloud:
    gateway:
      default-filters: # 공통 필터
        - name: GlobalFilter
          args:
            # 전달 하고자 하는 파라미터 값
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service # User Service 포워드
          uri: lb://USER-SERVICE # 요청이 조건에 따라 "이동 예정인" 주소
          predicates:
            # 해당 URI로 들어오면 포워딩이 됨.
            # 하지만, UserController 또한!! /user-service 로 설정해서 구현해야 함
            - Path=/user-service/**
          filters:
#            - AddRequestHeader=user-request, user-request-header
#            - AddResponseHeader=user-reponse, user-response-header
            - CustomFilter
            - name: LoggingFilter # 추가적인 파라미터가 존재 -> name 지정
              args:
                baseMessage: Hi, I'm your logging
                preLogger: true
                postLogger: true
        - id: catalog-service # Catalog Service 포워드
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
        - id: order-service # Order Service 포워드
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**