server:
  port: 8082 # 0으로 설정하면 random port를 사용한다는 의미 -> port의 충돌 X

spring:
  application:
    name: catalog-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msa-catalog?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop # 서비스 실행 시, 데이터를 자동으로 등록
      # update -> 삭제안하고싶을때 #none -> 배포시에(운영환경)
    properties:
      hibernate:
        default_batch_fetch_size: 500
        #        show_sql: false
        format_sql: true
    open-in-view: false
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true # 유레카 등록
    fetch-registry: true # 외부에서 검색 가능 -> eureka 서버로부터 인스턴스의 정보를 주기적으로 가져올것인지 설정
    service-url: #유레카 서버의 위치
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    org.hibernate.SQL: debug
    com.study: debug