server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git: # ?????? ??? ????? ????? ??
          uri: https://github.com/daisy6365/spring-cloud-config
